drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db, check_password_hash

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    userform = UserLoginForm()

    try:
        if request.method == 'POST' and userform.validate_on_submit():
            email = userform.email.data
            username = userform.username.data
            password = userform.password.data
            print(email, password)

            user = User(email, username, password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('auth.signin'))        
            
        
    except:
        raise Exception('Invalid Form Data. Please Check your form')
    
    return render_template('signup.html', form=userform)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    userform = UserLoginForm()


    try:
        if request.method == "POST" and userform.validate_on_submit():
            email = userform.email.data
            username = userform.username.data
            password = userform.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in via: Email/Password', 'auth-success')
                return redirect(url_for('site.profile')) # Comeback to here and redirect to profile
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=userform)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from drone_inventory.forms import DroneForm
from drone_inventory.models import Drone, db 
from drone_inventory.helpers import random_joke_generator


site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    print('look at this cool project. Would you just look at it')
    return render_template('index.html')

@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    droneform = DroneForm()

    try:
        if request.method == 'POST' and droneform.validate_on_submit():
            name = droneform.name.data
            description = droneform.description.data
            price = droneform.price.data
            camera_quality = droneform.camera_quality.data
            flight_time = droneform.flight_time.data
            max_speed = droneform.max_speed.data
            dimensions = droneform.dimensions.data
            weight = droneform.weight.data
            cost_of_production = droneform.cost_of_production.data
            series = droneform.series.data
            if droneform.dad_joke.data:
                random_joke = droneform.dad_joke.data
            else:
                random_joke = random_joke_generator()
            user_token = current_user.token

            drone = Drone(name, description, price, camera_quality, flight_time, max_speed, dimensions, weight, cost_of_production, series, random_joke, user_token)

            db.session.add(drone)
            db.session.commit()

            return redirect(url_for('site.profile'))
        
    except:
        raise Exception('Drone not created, please check your form and try again')
    
    user_token = current_user.token
    drones = Drone.query.filter_by(user_token=user_token)


    return render_template('profile.html', form=droneform, drones=drones)

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>

    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
        </div>

        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{url_for('site.profile')}}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('auth.logout')}}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>


    <!-- End Nav Bar -->

    {% block content %}
    {% endblock content %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/droneform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset class="name-field">
            {{ form.name.label }}
            {{ form.name(class='form-control', placeholder='Name') }}
        </fieldset>
        <fieldset class="description-field">
            {{ form.description.label }}
            {{ form.description(class='form-control', placeholder='Description') }}
        </fieldset>
        <fieldset class="price-field">
            {{ form.price.label }}
            {{ form.price(class='form-control', placeholder='Price') }}
        </fieldset>
        <fieldset class="camera-field">
            {{ form.camera_quality.label }}
            {{ form.camera_quality(class='form-control', placeholder='Camera Quality') }}
        </fieldset>
        <fieldset class="flight-field">
            {{ form.flight_time.label }}
            {{ form.flight_time(class='form-control', placeholder='Flight Time') }}
        </fieldset>
        <fieldset class="speed-field">
            {{ form.max_speed.label }}
            {{ form.max_speed(class='form-control', placeholder='Max Speed') }}
        </fieldset>
        <fieldset class="dimensions-field">
            {{ form.dimensions.label }}
            {{ form.dimensions(class='form-control', placeholder='Dimensions') }}
        </fieldset>
        <fieldset class="weight-field">
            {{ form.weight.label }}
            {{ form.weight(class='form-control', placeholder='Weight') }}
        </fieldset>
        <fieldset class="cost-field">
            {{ form.cost_of_production.label }}
            {{ form.cost_of_production(class='form-control', placeholder='Cost of Production') }}
        </fieldset>
        <fieldset class="series-field">
            {{ form.series.label }}
            {{ form.series(class='form-control', placeholder='Series') }}
        </fieldset>
        <fieldset class="joke-field">
            {{ form.dad_joke.label }}
            {{ form.dad_joke(class='form-control', placeholder='Dad Joke') }}
        </fieldset>
        
        {{ form.submit_button(class='btn btn-primary btn-block mt-2')}}
    </div>
</form>

drone_inventory/templates/forms.html
<!-- HTML produced & used by our Flask Form -->

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class='form-control', placeholder = "Place Username Here...")}}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class='form-control', placeholder = "Place Password Here...")}}
        </fieldset>

        <!-- Submit Button Field -->
        {{ form.submit_button(class='btn btn-primary btn-block')}}
    </div>
</form>